[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmp = "0.8.12"
rmp-serde = "1.1.2"
rmpv = "1.0.1"
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.114"
